### ISSUE TITLE
Reverse release.geneontology.org/ sort order, increase default display count for usability

### ISSUE THREAD

**Issue by suzialeksander** [geneontology/archive-reconstruction#10]
release.geneontology.org/ currently sorts old->new as default.  Can we just flip this so it's new-> old? 

Most users (including me) are more interested in releases from 2020-2021ish than the 2004 releases.

**Comment by lpalbou** [comment]
Since this now contains both the archive and the current releases, I also think it's more logical to have newer releases first. 

Columns Last modified and Timestamps are now hidden since the "Last modified doesn't reflect the date of the release in any way and Timestamps is not really helpful either.

I have merged my code (https://github.com/lpalbou/aws-js-s3-explorer/pull/2) and you can see the resulting changes on my temporary site: http://release.geneontology.xyz/.  To take effect on the go site, only @kltm can deploy the changes with the usual command line:

```
python3 s3_add_index.py -o <bucket_name>
```

**Comment by suzialeksander** [comment]
This looks better as far as hiding 'Last Modified'/etc. but on http://release.geneontology.xyz/ I only see three entries, and the releases appear to still be in old -> new order

**Comment by lpalbou** [comment]
@suzialeksander release.geneontology.xyz is my test site as I don't have the privileges to deploy on release.geneontology.org and indeed, I only added 3 releases there for the illustration so no issue here. 

For still showing older releases first, you probably have to clear your cache as it does display the newer releases for me after a refresh:

![Screen Shot 2021-01-25 at 9 48 29 PM](https://user-images.githubusercontent.com/24249870/105805560-11c74e80-5f57-11eb-844d-144cc7893cdb.png)

Once @kltm deploy the changes to release.geneontology.org, you will see all the releases as usual.

**Comment by lpalbou** [comment]
Done.

**Comment by pgaudet** [comment]
Thanks !
